
base_url = "https://ads40.github.io/reading-panini/"
title = "Reading Panini"
description = "Learning about Panini's Astadhyayi and the Vyakarana tradition."
theme = "apollo"
taxonomies = [{ name = "tags" }]
compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "atom.xml"

[markdown]
highlight_code = true

[extra]
theme = "auto"
socials = [
    # Configure socials here
]
menu = [
    # Configure menu bar here
]

# Whether to show links to earlier and later posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Read more"

# - "combined" -- combine like so: "page_title | main_title",
#                 or if page_title is not defined or empty, fall back to `main_title`
page_titles = "combined"
