
base_url = "https://ads40.github.io/reading-panini/"
title = "Reading Pāṇini"
description = "Learning about Pãṇini's Aṣṭadhyãyĩ and the vyãkaraṇa tradition."
theme = "apollo"
taxonomies = [{ name = "tags" }]
compile_sass = true
build_search_index = true
generate_feed = true
feed_filename = "atom.xml"

[markdown]
highlight_code = true

taxonomies = [{ name = "tags" }, { name = "texts" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[extra]
theme = "auto"
socials = [
    { name = "linkedin", url = "https://www.linkedin.com/in/ads40/", icon = "linkedin" },
    { name = "github", url = "https://github.com/ads40/reading-panini", icon = "github" },
]
menu = [
    { name = "/posts", url = "/posts", weight = 2 },
    { name = "/about", url = "/about", weight = 1 },
    { name = "/biblio", url = "/biblio", weight = 3 },
    { name = "/glossary", url = "/glossary", weight = 4 },
]
